# URL de connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/dbassigame

# Identifiants de connexion
spring.datasource.username=postgres
spring.datasource.password=99achille
server.port=8081

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# Taille maximale autorisée pour l'upload d'images de produits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
